$(document).ready(function(){
   $('#up-btn').click(function(){
      $('#player').animate({top:'-=100px'},1000);
   });
   $('#down-btn').click(function(){
      $('#player').animate({top:'+=100px'},1000);
   });
   $('#left-btn').click(function(){
      $('#player').animate({left:'-=100px'},1000);
   });
   $('#right-btn').click(function(){
      $('#player').animate({left:'+=100px'},1000);
   });
   $('#in-btn').click(function(){
      $('#player').fadeIn();
   });
   $('#out-btn').click(function(){
      $('#player').fadeOut();
   });
   $("div").mouseenter(function(){
        $("div").fadeTo("fast",1);
    });
    $("div").mouseleave(function(){
        $("div").fadeTo("fast",0.5);    
    });
});
